-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 10:05:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema foodOnOneClick
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foodOnOneClick
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foodOnOneClick` DEFAULT CHARACTER SET utf8 ;
USE `foodOnOneClick` ;

-- -----------------------------------------------------
-- Table `foodOnOneClick`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`avg_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`avg_cost` (
  `avg_cost_id` INT NOT NULL AUTO_INCREMENT,
  `cost` INT NOT NULL,
  PRIMARY KEY (`avg_cost_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`restaurant_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`restaurant_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`delivery_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`delivery_fee` (
  `delivery_fee_id` INT NOT NULL AUTO_INCREMENT,
  `fee` INT NOT NULL,
  PRIMARY KEY (`delivery_fee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`manager` (
  `email_id` VARCHAR(80) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`restaurant` (
  `restaurant_name` VARCHAR(45) NOT NULL,
  `image_name` VARCHAR(120) NOT NULL,
  `city_city_id` INT NOT NULL,
  `avg_cost_avg_cost_id` INT NOT NULL,
  `restaurant_category_category_id` INT NOT NULL,
  `delivery_fee_delivery_fee_id` INT NOT NULL,
  `manager_email_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`manager_email_id`),
  INDEX `fk_restaurant_city1_idx` (`city_city_id` ASC) VISIBLE,
  INDEX `fk_restaurant_avg_cost1_idx` (`avg_cost_avg_cost_id` ASC) VISIBLE,
  INDEX `fk_restaurant_restaurant_category1_idx` (`restaurant_category_category_id` ASC) VISIBLE,
  INDEX `fk_restaurant_delivery_fee1_idx` (`delivery_fee_delivery_fee_id` ASC) VISIBLE,
  INDEX `fk_restaurant_manager1_idx` (`manager_email_id` ASC) VISIBLE,
  UNIQUE INDEX `city_city_id_UNIQUE` (`city_city_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `foodOnOneClick`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_avg_cost1`
    FOREIGN KEY (`avg_cost_avg_cost_id`)
    REFERENCES `foodOnOneClick`.`avg_cost` (`avg_cost_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_restaurant_category1`
    FOREIGN KEY (`restaurant_category_category_id`)
    REFERENCES `foodOnOneClick`.`restaurant_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_delivery_fee1`
    FOREIGN KEY (`delivery_fee_delivery_fee_id`)
    REFERENCES `foodOnOneClick`.`delivery_fee` (`delivery_fee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_manager1`
    FOREIGN KEY (`manager_email_id`)
    REFERENCES `foodOnOneClick`.`manager` (`email_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`customer` (
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email_id` VARCHAR(80) NOT NULL,
  `image_name` VARCHAR(120) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `city_city_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `address` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`email_id`),
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE,
  INDEX `fk_customer_city1_idx` (`city_city_id` ASC) VISIBLE,
  INDEX `fk_customer_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `foodOnOneClick`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `foodOnOneClick`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`permissibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`permissibility` (
  `permissibilty_id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`permissibilty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`item_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`item_category` (
  `item_category_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(45) NOT NULL,
  `item_price` VARCHAR(45) NOT NULL,
  `image_name` VARCHAR(440) GENERATED ALWAYS AS () VIRTUAL,
  `permissibility_permissibilty_id` INT NOT NULL,
  `item_category_item_category_id` INT NOT NULL,
  `restaurant_restaurant_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_item_permissibility1_idx` (`permissibility_permissibilty_id` ASC) VISIBLE,
  INDEX `fk_item_item_category1_idx` (`item_category_item_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_permissibility1`
    FOREIGN KEY (`permissibility_permissibilty_id`)
    REFERENCES `foodOnOneClick`.`permissibility` (`permissibilty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_item_category1`
    FOREIGN KEY (`item_category_item_category_id`)
    REFERENCES `foodOnOneClick`.`item_category` (`item_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `review` VARCHAR(445) NOT NULL,
  `item_item_id` INT NOT NULL,
  `customer_email_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_review_item1_idx` (`item_item_id` ASC) VISIBLE,
  INDEX `fk_review_customer1_idx` (`customer_email_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_item1`
    FOREIGN KEY (`item_item_id`)
    REFERENCES `foodOnOneClick`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_customer1`
    FOREIGN KEY (`customer_email_id`)
    REFERENCES `foodOnOneClick`.`customer` (`email_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`ratings` (
  `ratings_id` INT NOT NULL AUTO_INCREMENT,
  `rating_value` INT NOT NULL,
  `item_item_id` INT NOT NULL,
  `customer_email_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ratings_id`),
  INDEX `fk_ratings_item1_idx` (`item_item_id` ASC) VISIBLE,
  INDEX `fk_ratings_customer1_idx` (`customer_email_id` ASC) VISIBLE,
  CONSTRAINT `fk_ratings_item1`
    FOREIGN KEY (`item_item_id`)
    REFERENCES `foodOnOneClick`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_customer1`
    FOREIGN KEY (`customer_email_id`)
    REFERENCES `foodOnOneClick`.`customer` (`email_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(95) NOT NULL,
  `customer_email_id` VARCHAR(80) NOT NULL,
  `status_id` INT NOT NULL,
  `restaurant_manager_email_id` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_customer1_idx` (`customer_email_id` ASC) VISIBLE,
  INDEX `fk_order_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_order_restaurant1_idx` (`restaurant_manager_email_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_email_id`)
    REFERENCES `foodOnOneClick`.`customer` (`email_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `foodOnOneClick`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_restaurant1`
    FOREIGN KEY (`restaurant_manager_email_id`)
    REFERENCES `foodOnOneClick`.`restaurant` (`manager_email_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `foodOnOneClick`.`order_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foodOnOneClick`.`order_has_item` (
  `order_order_id` INT NOT NULL,
  `item_item_id` INT NOT NULL,
  PRIMARY KEY (`order_order_id`, `item_item_id`),
  INDEX `fk_order_has_item_item1_idx` (`item_item_id` ASC) VISIBLE,
  INDEX `fk_order_has_item_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_item_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `foodOnOneClick`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_item_item1`
    FOREIGN KEY (`item_item_id`)
    REFERENCES `foodOnOneClick`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
